/*
 * This source file was generated by the Gradle 'init' task
 */

#ifndef APP_H
#define APP_H

#include <string>

namespace ejemplo {
    class Greeter {
        public:
        std::string greeting();
        int sumar(int a, int b);
    };
}

#endif
