/*
 * This source file was generated by the Gradle 'init' task
 */

#include "app.h"
#include <cassert>

void pruebassuma() {
    ejemplo::Greeter objGreeter;
    assert(objGreeter.sumar(1,2) == 3);
    assert(objGreeter.sumar(-1,1) == 0);
    assert(objGreeter.sumar(10,10) == 20);
}

int main() {
    ejemplo::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    pruebassuma();
    return 0;
}
