/*
 * This source file was generated by the Gradle 'init' task
 */

#include "app.h"
#include <cassert>

void pruebassuma() {
    ejemplo::Greeter objGreeter;
    assert(objGreeter.sumar(1,2) == 3);
    assert(objGreeter.sumar(-1,1) == 0);
    assert(objGreeter.sumar(10,10) == 20);
}

void pruebaresta() {
    ejemplo::Greeter objGreeter;
    assert(objGreeter.restar(5,3) == 2);
    assert(objGreeter.restar(0,0) == 0);
    assert(objGreeter.restar(10,5) == 5);
    assser(objGreeter.restar(1,3) == -2);
}

int main() {
    ejemplo::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    pruebassuma();
    return 0;
}
