/*
 * This source file was generated by the Gradle 'init' task
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"

std::string ejemplo::Greeter::greeting() {
    return std::string("Hello, World!");
}

int ejemplo::Greeter::sumar(int a, int b) {
    return a+b;
}

int ejemplo::Greeter::restar(int a, int b) {
    return a-b;
}

int main () {
    ejemplo::Greeter greeter;
    std::cout << greeter.greeting() << std::endl;
    return 0;
}
